return {
  {
    "AstroNvim/astroui",
    opts = {
      icons = {
        ActiveLSP = "",
        ActiveTS = " ",
        ArrowLeft = "",
        ArrowRight = "",
        Bookmarks = "",
        BufferClose = "",
        DapBreakpoint = "",
        DapBreakpointCondition = "",
        DapBreakpointRejected = "",
        DapLogPoint = "",
        DapStopped = "",
        Debugger = "",
        DefaultFile = "",
        Diagnostic = "",
        DiagnosticError = "",
        DiagnosticHint = "",
        DiagnosticInfo = "",
        DiagnosticWarn = "",
        Ellipsis = "",
        FileNew = "",
        FileModified = "",
        FileReadOnly = "",
        FoldClosed = "",
        FoldOpened = "",
        FolderClosed = "",
        FolderEmpty = "",
        FolderOpen = "",
        Git = "",
        GitAdd = "",
        GitBranch = "",
        GitChange = "",
        GitConflict = "",
        GitDelete = "",
        GitIgnored = "",
        GitRenamed = "",
        GitStaged = "",
        GitUnstaged = "",
        GitUntracked = "",
        LSPLoaded = "",
        LSPLoading1 = "",
        LSPLoading2 = "",
        LSPLoading3 = "",
        MacroRecording = "",
        Package = "",
        Paste = "",
        Refresh = "",
        Search = "",
        Selected = "",
        Session = "",
        Sort = "",
        Spellcheck = "",
        TabClose = "",
        Terminal = "",
        Window = "",
        WordFile = "",
      },
    },
  },
  {
    "nvim-mini/mini.icons",
    optional = true,
    opts = {
      lsp = {
        array = { glyph = "  " },
        boolean = { glyph = " 󰨙 " },
        class = { glyph = " 󰯳 " },
        codeium = { glyph = " 󰘦 " },
        color = { glyph = " 󰰠 " },
        control = { glyph = "  " },
        collapsed = { glyph = " > " },
        constant = { glyph = " 󰯱 " },
        constructor = { glyph = "  " },
        copilot = { glyph = "  " },
        enum = { glyph = " 󰯹 " },
        enummember = { glyph = "  " },
        event = { glyph = "  " },
        field = { glyph = "  " },
        file = { glyph = "  " },
        folder = { glyph = "  " },
        ["function"] = { glyph = " 󰡱 " },
        interface = { glyph = " 󰰅 " },
        key = { glyph = "  " },
        keyword = { glyph = " 󱕴 " },
        method = { glyph = " 󰰑 " },
        module = { glyph = " 󰆼 " },
        namespace = { glyph = " 󰰔 " },
        null = { glyph = "  " },
        number = { glyph = " 󰰔 " },
        object = { glyph = " 󰲟 " },
        operator = { glyph = "  " },
        package = { glyph = " 󰰚 " },
        property = { glyph = " 󰲽 " },
        reference = { glyph = " 󰰠 " },
        snippet = { glyph = "  " },
        string = { glyph = "  " },
        struct = { glyph = " 󰰣 " },
        tabnine = { glyph = " 󰏚 " },
        text = { glyph = " 󱜥 " },
        typeparameter = { glyph = " 󰰦 " },
        unit = { glyph = " 󱜥 " },
        value = { glyph = "  " },
        variable = { glyph = " 󰫧 " },
      },
    },
  },
}
